name: "🧪 Static Analysis"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/static-analysis.yml'
jobs:
  static-analysis:
    name: "🧬 PHP Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "🛑  Stop Previous Same Workflow Runs"
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💽  Installing PHP , Composer , CS2PR"
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v1

      - name: "💽  Installing Composer Packages"
        run: composer install --no-dev

      - name: "💽  Installing PHPStan Package"
        run: |
          composer global require szepeviktor/phpstan-wordpress
          composer global require php-stubs/woocommerce-stubs
          composer global require phpstan/extension-installer

      - name: "⚡  Setup PHPStan File"
        run: |
          echo "parameters:
                    level: 8
                    paths:
                        - inc/
          " > $GITHUB_WORKSPACE/phpstan.neon

      - name: "🧪 Test"
        uses: php-actions/phpstan@v2
        with:
          configuration: ./phpstan.neon
