name: "🧪 Static Analysis"

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/static-analysis.yml'
jobs:
  static-analysis:
    name: "🧬 PHP Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "🛑  Stop Previous Same Workflow Runs"
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "💽  Installing PHP , Composer , CS2PR"
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: '7.4'
          coverage: xdebug
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: phpstan, composer

      - name: "💽  Installing PHPStan Version"
        run:  phpstan --version

      - name: "💽  Installing Composer Packages"
        run: composer install

      - name: "💽  Installing PHPStan Version"
        run: phpstan --version

      - name: "⚡  Setup PHPStan File"
        run: |
          echo "parameters:
                    level: 8
                    paths:
                        - ./a.php
          " > $GITHUB_WORKSPACE/phpstan.neon

      - name: "🧪 Test"
        continue-on-error: true
        run: phpstan analyze --xdebug
